server:
  port: 8082

# oauth2 callback URL
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8085/auth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/