apiVersion: v1
kind: Service
metadata:
  name: spmia-service
spec:
  type: NodePort
  selector:
    app: eurekaserver
  ports:
  - name: eureka-service
    protocol: TCP
    port: 8761
    targetPort: 8761
    nodePort: 30761
  - name: config-service
    protocol: TCP
    port: 8889
    targetPort: 8889
    nodePort: 30889


