apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  username: YWRtaW4= # echo -n admin | base64
  password: dGVzdDEyMzQ=  # echo -n test1234 | base64

# decode, e.g.: echo -n YWRtaW4= | base64 --decode