apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: xdubuntu1810mini:5000/redis:alpine
        ports:
        - containerPort: 6379
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    name: redis-port
    targetPort: 6379
    nodePort: 30379
    protocol: TCP
  selector:
    app: redis