apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  type: NodePort
  selector:
    app: configserver
  ports:
  - name: config-service
    protocol: TCP
    port: 8889
    targetPort: 8889
    nodePort: 30889