apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  labels:
    app: flaskapp
spec:
  selector:
    app: flaskapp
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30090

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flaskapp-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapp
        version: v1
    spec:
      containers:
      - name: flaskapp
        image: xdubuntu1810mini:5000/flaskdemoxdli:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: version
          value: v1
        - name: test1
          value: "50"
        - name: test2
          value: "200"

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flaskapp-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapp
        version: v2
    spec:
      containers:
      - name: flaskapp
        image: xdubuntu1810mini:5000/flaskdemoxdli:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: version
          value: v2
        - name: test1
          value: "50"
        - name: test2
          value: "200"
