apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  namespace: istio-system
  labels:
    app: flaskapp
    version: v1
spec:
  selector:
    app: flaskapp
    version: v1
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30090

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flaskapp
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapp
        version: v1
    spec:
      containers:
      - name: flaskapp
        image: xdubuntu1810mini:5000/flaskdemoxdli:v1
        imagePullPolicy: Always
        env:
        - name: test1
          value: "50"
        - name: test2
          value: "200"
