apiVersion: v1
kind: Service
metadata:
  name: flaskappdup
  namespace: istio-system
  labels:
    app: flaskappdup
    version: v1
spec:
  selector:
    app: flaskappdup
    version: v1
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flaskappdup
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskappdup
        version: v1
    spec:
      containers:
      - name: flaskappdup
        image: xdubuntu1810mini:5000/flaskdemoxdli:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: test1
          value: "50"
        - name: test2
          value: "200"
