kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
        app: kafka
    spec:
      containers:
      - name: kafka
        image: xdubuntu1810mini:5000/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-service"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_CREATE_TOPICS
          value: "orgChangeTopic:1:1"

# 使用kafka-service和zookeeper-service这类方式只能支持cluster内部的使用，对于外部访问会有问题
# 如果使用外部访问，那么IP和端口都应该切换到外部可访问的地址，同时也需要zookeeper、broker之间都能够访问
