server:
  port: 8082
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
            destination:  orgChangeTopic
            content-type: application/json
            group: licensingGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost