apiVersion: v1
kind: Pod
metadata:
  name: mypod1
spec:
  containers:
  - image: busybox
    name: mypod1
    args:
    - /bin/sh
    - -c
    - sleep 10; touch /tmp/healthy; sleep 30000
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: myconfigmap
      items:
        - key: logging.conf
          path: myapp/logging.conf