apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: licensingserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: licensingserver
    spec:
      containers:
      - name: licensingserver
        image: xdubuntu1810mini:5000/tmx-licensing-service:springcloud
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        resources: {}
        env:
        - name: PROFILE
          value: default
        - name: SERVER_PORT
          value: "8082"
        - name: EUREKASERVER_URI
          value: http://eurekaserver:8761/eureka/
        - name: CONFIGSERVER_URI
          value: http://configserver:8889
        - name: ZIPKIN_URI
          value: http://zipkin-service:9411
        - name: KAFKASERVER_URI
          value: kafka-service
        - name: ZKSERVER_URI
          value: zookeeper-service
        - name: DATABASESERVER_PORT
          value: "5432"
        - name: EUREKASERVER_PORT
          value: "8761"
        - name: REDIS_PORT
          value: "6379"
        - name: CONFIGSERVER_PORT
          value: "8889"
        - name: ZUULSERVER_PORT
          value: "5555"
        - name: KAFKASERVER_PORT
          value: "9092"
        - name: ZIPKIN_PORT
          value: "9411"
        - name: ENCRYPT_KEY
          value: IMSYMMETRIC
        - name: DEBUG_MODE
          value: "0"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: licensingservice
spec:
  type: NodePort
  selector:
    app: licensingserver
  ports:
  - name: licensingservice
    protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 30082