server:
  port: 5555
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1

#
#zuul:
#  routes:
#    organizationservice: /organization/**
#    licensingservice: /licensing/**
#  ignored-services: '*'
#  prefix: /api
#