apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: organizationserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: organizationserver
    spec:
      containers:
      - name: organizationserver
        image: xdubuntu1810mini:5000/tmx-organization-service:springcloud
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
        resources: {}
        env:
        - name: PROFILE
          value: default
        - name: SERVER_PORT
          value: "8086"
        - name: EUREKASERVER_URI
          value: http://eurekaserver:8761/eureka/
        - name: CONFIGSERVER_URI
          value: http://configserver:8889
        - name: ZIPKIN_URI
          value: http://zipkin-service:9411
        - name: KAFKASERVER_URI
          value: kafka-service
        - name: ZKSERVER_URI
          value: zookeeper-service
        - name: DATABASESERVER_PORT
          value: "5432"
        - name: EUREKASERVER_PORT
          value: "8761"
        - name: CONFIGSERVER_PORT
          value: "8889"
        - name: ZUULSERVER_PORT
          value: "5555"
        - name: KAFKASERVER_PORT
          value: "9092"
        - name: ZIPKIN_PORT
          value: "9411"
        - name: ENCRYPT_KEY
          value: IMSYMMETRIC
        - name: DEBUG_MODE
          value: false
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: organizationservice
spec:
  type: NodePort
  selector:
    app: organizationserver
  ports:
  - name: organizationservice
    protocol: TCP
    port: 8086
    targetPort: 8086
    nodePort: 30086