server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
         encrypt:
           enabled: false
         native:
           searchLocations: file:///home/xiaodong/Gitroot/spmia/spmia-chapter2/confsvr/src/main/resources/config/licensingservice



