server:
  port: 8889
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka/
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        git:
#          uri: http://gitlab.xdubuntu1804.com/brynelee/config-repo.git
          uri: http://xdubuntu1810/brynelee/config-repo.git
          searchPaths: licensingservice,organizationservice,zuulservice
          username: brynelee
          password: "{cipher}a8d9d17d465f8b31500c24887f1fed7f0d6adcd50e2b473c9e1c9a7e35e6b17c"