apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"bryneleexdli.com": ["192.168.3.190"]}
  upstreamNameservers: |
    ["192.168.3.1"]


# kube-dns已经废除了，所以不好用了
