apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    -  mesh
    - "httpbin.microservice.rocks"
  - port:
      number: 443
      name: https-rocks
      protocol: HTTPS
    tls:
      mode: MUTUAL
      serverCertificate: /etc/istio/ingressgateway-certs/httpbin.microservice.rocks.crt
      privateKey: /etc/istio/ingressgateway-certs/httpbin.microservice.rocks.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/ca.crt
    hosts:
    - "httpbin.microservice.rocks"