apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafkaserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafkaserver
    spec:
      containers:
      - name: kafkaserver
        image: xdubuntu1810mini:5000/kafka
        ports:
        - containerPort: 9092
        - containerPort: 2181
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: kafkaserver
spec:
  type: NodePort
  selector:
    app: kafkaserver
  ports:
  - name: kafkaserver-service
    protocol: TCP
    port: 9092
    targetPort: 9092
    nodePort: 30092
  - name: zookeeper-service
    protocol: TCP
    port: 2181
    targetPort: 2181
    nodePort: 30181
