apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eurekaserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: xdubuntu1810mini:5000/tmx-eurekasvr:springcloud
        ports:
        - containerPort: 8761
#        readinessProbe:
#          httpGet:
#            scheme: HTTP
#            path: /health
#            port: 8761
#          initialDelaySeconds: 10
#          periodSeconds: 5
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /health
            port: 8761
          initialDelaySeconds: 10
          periodSeconds: 5
#      nodeSelector:
#        xdlabel: node01
      restartPolicy: Always